apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewsapi
  namespace: fcg-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewsapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: reviewsapi
    spec:
      containers:
        - name: reviewsapi
          image: anabordinhon/reviews-api-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: MongoDB__DatabaseName
              value: "fcg_reviews"
            - name: MongoDB__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: reviewsapi-secret
                  key: MongoDB__ConnectionString
            - name: Jwt__SecretKey
              valueFrom:
                secretKeyRef:
                  name: reviewsapi-secret
                  key: Jwt__SecretKey
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
